name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  pages-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Assemble files to be published
      run: |
        mkdir -p public
        cp -r index.html jeu.js style.css img public/
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: public/
        retention-days: 30
  pages-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: pages-build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
